cheese_roquefort_price = "12.50 zl"
cheese_roq_ingridient = "Cheese Roquefort"
cheese_stilton_price = "11.24 zl"
cheese_stilton_ingridient = "Cheese Stilton"
cheese_brie_price = "9.30 zl"
cheese_brie_ingridient = "Cheese Brie"
cheese_gauda_price = "8.55 zl"
cheese_gauda_ingridient = "Cheese Gauda"
cheese_edam_price = "11.00 zl"
cheese_edam_ingridient = "Cheese Edam"
cheese_parmesan_price = "16.50 zl"
cheese_parm_ingridient = "Cheese Parmesan"
cheese_mozzarella_price = "14.00 zl"
cheese_mozz_ingridient = "Cheese Mozzarella"
cheese_slovak_price = "122.32 zl"
cheese_slov_ingridient = "Slovak sheep's milk cheese"
my_report = f"{cheese_roq_ingridient} = {cheese_roquefort_price}, {cheese_stilton_ingridient} = {cheese_stilton_price}, {cheese_brie_ingridient} = {cheese_brie_price}, {cheese_gauda_ingridient} = {cheese_gauda_price}, {cheese_edam_ingridient} = {cheese_edam_price}, {cheese_parm_ingridient} = {cheese_parmesan_price}, {cheese_mozz_ingridient} = {cheese_mozzarella_price}, {cheese_slov_ingridient} = {cheese_slovak_price}"
print(my_report)